include: package:flutter_lints/flutter.yaml
# analyzer:
#   strong-mode:
#     implicit-casts: false
#     implicit-dynamic: false
#   errors:
#     unused_element: warning
#     unused_local_variable: warning

# linter:
#   rules:
#     - prefer_const_constructors
#     - prefer_const_declarations
#     - prefer_const_literals_to_create_immutables
